auth_groups:
  - "myADGroupWhoIsAllowed"

active_directory:
  account_suffix: "@ad.suffix"
  base_dn: "DC=x,DC=y,DC=com"
  domain_controllers:
    - "pdc.x.y.com"

weighted-dns:
  - name: "myrecord.acme.com"
   zone: "acme.com"
   zoneid: "1234567890"

  - name: "myrecord.acme.com"
    zone: "acme.com"
    zoneid: "1234567890"
